development:
  adapter: postgresql
  database: my_profile_development
  pool: 5
  timeout: 5000
  host: localhost
  username: profileapp
  password: ror2ror
test:
  adapter: postgresql
  database: my_profile_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_profile_production
  pool: 5
  timeout: 5000